// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using final.Models;

namespace final.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20200417131459_shubhi")]
    partial class shubhi
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.0-preview.2.20159.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("final.Models.EmployeeLeaveMapping", b =>
                {
                    b.Property<int>("emlid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("employeeid")
                        .HasColumnType("int");

                    b.Property<string>("leaveenddate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leaveid")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("leavestartdate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("emlid");

                    b.ToTable("EmpLeaves");
                });

            modelBuilder.Entity("final.Models.Employee_details", b =>
                {
                    b.Property<int>("employeeid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("dob")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("doj")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("employeename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("salary")
                        .HasColumnType("int");

                    b.HasKey("employeeid");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("final.Models.Leave", b =>
                {
                    b.Property<int>("leaveid")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("leavename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("maxleaveallowed")
                        .HasColumnType("int");

                    b.HasKey("leaveid");

                    b.ToTable("Leave");
                });
#pragma warning restore 612, 618
        }
    }
}
